### ISSUE TITLE
Fix typeo on registration 

### ISSUE THREAD

**Issue by stevepolitodesign** [stevepolitodesign/my_site_archive#145]
@mvanderleest I could have used you on this.

![CleanShot 2021-06-10 at 14 07 03](https://user-images.githubusercontent.com/5122678/121575310-38ad8b00-c9f5-11eb-986b-4fff6c4257b5.png)

**Comment by mvanderleest** [comment]
@stevepolitodesign but where's the fun in that? 🙃
